version: '3.8'

services:
  backend:
    image: hydro-sys
    build: .
    container_name: hydro-sys-backend
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/hydro-sys
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16.5-alpine
    container_name: hydro-sys-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
