# Generated by Django 5.1.5 on 2025-02-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroponicSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NFT", "Nutrient Film Technique"),
                            ("DWC", "Deep Water Culture"),
                            ("Ebb and Flow", "Ebb and Flow"),
                            ("Aeroponics", "Aeroponics"),
                            ("Drip", "Drip System"),
                            ("Wick", "Wick System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
