# Generated by Django 5.1.5 on 2025-02-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph", models.FloatField(help_text="In the pH scale (0-14)")),
                ("temperature", models.FloatField(help_text="In Celcius (°C)")),
                ("tds", models.FloatField(help_text="Parts per milion (ppm)")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="systems.hydroponicsystem",
                    ),
                ),
            ],
        ),
    ]
