# Generated by Django 5.1.6 on 2025-02-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0002_measurement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hydroponicsystem",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
